services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MOTD: "A §l§cMinecraft§r §nserver"
      OPS: |
        MrJvfd3
      ICON: "http://..../some/other/image.png"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
