services:
  mc:
    image: itzg/minecraft-server
    tty: TRUE
    stdin_open: TRUE
    restart: unless-stopped

    ports:
      - '25565:25565'
    
    environment:
      EULA: 'TRUE'
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: ${API_KEY} # A CurseForge API key is required to use this feature. Go to their developer console, generate an API key, and set the environment variable CF_API_KEY. This is required for the MODPACK_PLATFORM: AUTO_CURSEFORGE feature to work.
      # CF_PAGE_URL: 'https://www.curseforge.com/minecraft/modpacks/deb'
      # CF_FILE_ID: 6042392 # 20250101 - Client
      CF_FILE_ID: 6046147 # 20250102 - Client
      CF_SLUG: 'deb'

      MEMORY: 4G
      MOTD: "\u00A76O período anual retornou 🥳🎄\u00A7r\n\u00A7lModpack:\u00A7r 20241231\u00A7r; \u00A7lMine Version:\u00A7r 1.20.1"
      SEED: 'lost'
      LEVEL: '20241231'
      SERVER_NAME: 'FastFreeMinecraftServer'
      OPS: 'MrJvfd3'
      ICON: 'https://raw.githubusercontent.com/jvfd3/FastFreeMinecraftServer/refs/heads/main/Files/Docker/Minecraft%20Loop.jpg'

      SPAWN_NPCS: TRUE
      ALLOW_FLIGHT: TRUE
      ALLOW_NETHER: TRUE
      ONLINE_MODE: FALSE
      SPAWN_ANIMALS: TRUE
      SPAWN_MONSTERS: TRUE
      GENERATE_STRUCTURES: TRUE
      ANNOUNCE_PLAYER_ACHIEVEMENTS: TRUE
      CF_FORCE_REINSTALL_MODLOADER: FALSE # (default is false): this can be set to true to force the modpack's declared modloader, such as Forge, to be reinstalled. This is useful if some of the modloader's files become corrupted.
    volumes:
      - ./data:/data # attach the relative directory 'data' to the container's /data path
      - ./modpacks:/modpacks:ro
